### ISSUE TITLE
ResetPasswordBundle v2.0

### ISSUE THREAD

**Issue by jrushlow** [SymfonyCasts/reset-password-bundle#290]
### _`2.x` branch is NOT production ready_

Version `2.0` is looking like it will be released in `2024`. Version `1.x` will be transitioned to security fixes only until it reaches its EOL in late 2024 / Q1 2025. New Features should be merged into `2.x` unless absolutely necessary to preserve BC in `1.x`

This issue will be updated to reflect any tasks required to get `2.0` out the door. Any issues concerning `2.0` should tag this thread / issue where appropriate.

## Todo's for release

- [ ] Determine base dependencies - Partially completed in #291 need to eval doctrine and `annotations`
- [x] Init `UPGRADE.md` to document path's forward to BC
- [ ] Update `CHANGELOG.md` for 2.x
- [ ] Totally Typed (properties, methods, returns, constructors)
- [x] `#[SensitiveParameter]` attributes for any secrets - #315 
- [ ] Eval / widen`doctrine/orm` dependency in `require-dev`. Does `ORM` 3 || 4 affect bundle internals outside of tests
- [ ] Eval / widen `doctrine/persistence` how does this affect bundle outside of tests
- [x] Check bundle `DependencyInjection`, `Resources/config/verify_email_services.xml`, & `VerifyEmailBundle::class` align with latest & greatest Symfony Bundle best practices - #312 
- [x] Translation file format's aligned with Symfony Translation best practices
- [x] Mark all classes `@final`, `@internal` where appropriate - #316 
- [ ] Eval implementation of PHPUnit `10`/`11`, at the very least ensure test suite is compatible w/ 10/11 where possible.
- [x] Update `.php-cs-fixer.dist.php` as required
- [x] Update `phpunit.xml.dist` as required
- [ ] Update `MakerBundle`, specifically, `make:reset-password` where applicable to prefer `2.x` usage
- [ ] Triage any existing issues / pulls - set milestone for `2.x` or `1.x` as required.
- [x] Remove phpstan `baseline`
- [x] Drop annotation support for entities #303
- [x] Implement `symfony/clock` component see #354

---

- [ ] Review / test entire code base
- [ ] Review / Sync `README.md` with bundle and `make:reset-password`

**Comment by laurentmuller** [comment]
Hi,
I have the just question about PHP version. Why do You use the version 8.3 ?
The version 8.2 is not sufficient ?
Thank
